### ISSUE TITLE
Update to Play 2.4.x with InjectedRoutesGenerator

### ISSUE THREAD

**Issue by mantsak** [brikis98/ping-play#12]
Fantastic webinar and exciting technology!

I tried to update the project to Play 2.4.x at

https://github.com/mantsak/ping-play/tree/2.4.x

My knowledge is not that deep to get the application running. I changed the Controller classes from `object`to `class`, but there is still some coding left. It would be great if this repositary can be updated. If you implement the changes in your code, I will delete my fork. Or update my fork with a pull request to keep your version according to your presentation.

**Comment by brikis98** [comment]
I just upgraded this repo to Play 2.4, but there are a few issues:

1. The Java examples no longer work, possibly due to a bug or design issue in Play 2.4 with compile-time dependency injection. I've filed #13 to track this.
2. The Docker image no longer builds due to a change in the progrium/busybox image. I've filed #14 to track this.

Talk about yak shaving :)
